### ISSUE TITLE
how to ignore master ASG on kube-aws

### ISSUE THREAD

**Issue by VinceMD** [hjacobs/kube-aws-autoscaler#43] opened 2017-11-13 22:09 UTC
I use kube-aws 0.9.8 and it seems jacobs/kube-aws-autoscaler does not ignore masters by default .

I haven't specified --include-master-nodes
But looking at the code, it looks like it's looking for tags on the EC2 or ASG?
I tried to add tag master=true to all controller and controller ASG without luck (Controller = master in Kube-aws terminology)

In kube-aws the master/controller ASG has the tag `kubernetes.io/role/master` with no value set

**Comment by hjacobs** [comment] 2017-11-14 08:51
This is a duplicate of #36.

**Closed by hjacobs** 2017-11-14 08:51 UTC
Labels: duplicate

**Comment by hjacobs** [comment] 2017-11-14 08:55
@VinceMD the autoscaler looks at node labels and `kube-aws` sets `node-role.kubernetes.io/master` (https://github.com/kubernetes-incubator/kube-aws/blob/062573d4c7fc49479e113490f139249ed92df345/core/controlplane/config/templates/cloud-config-controller#L278). Fixing #36 would also fix `kube-aws`.
